# Generated by Django 4.0 on 2026-05-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='marking_criteria',
            field=models.TextField(blank=True, help_text='Specify the criteria for grading this assignment.', null=True),
        ),
    ]
